[versions]
composeVersion = "1.5.4"
roomVersion = "2.5.2"
lifeCycleVersion = "2.6.2"
courierVersion = "0.2.8"
timberVersion = "5.0.1"
coreKtxVersion = "1.12.0"
retrofitVersion = "2.9.0"
daggerHiltVersion = "2.48.1"
accompanistVersion = "0.32.0"
mapsUtilVersion = "3.4.0"
composeMapsVersion = "2.15.0"
androidPluginVersion = "8.1.4"
appCompatVersion = "1.6.1"

[libraries]
#Logging
jakewharton-timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timberVersion" }

#Gojek Courier
courier-courier = { group = "com.gojek.courier", name = "courier", version.ref = "courierVersion" }
courier-gson = { group = "com.gojek.courier", name = "courier-message-adapter-gson", version.ref = "courierVersion" }
courier-stream = { group = "com.gojek.courier", name = "courier-stream-adapter-coroutines", version.ref = "courierVersion" }
courier-ping = { group = "com.gojek.courier", name = "workmanager-pingsender", version.ref = "courierVersion" }
courier-chucker = { group = "com.gojek.courier", name = "chuck-mqtt", version.ref = "courierVersion" }

#Androidx
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtxVersion" }
androidx-lifecycleRuntimeKtx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifeCycleVersion" }
androidx-lifecycleRuntimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifeCycleVersion" }
androidx-navigationCompose = { group = "androidx.navigation", name = "navigation-compose", version = "2.7.5" }
androidx-multidex = { group = "androidx.multidex", name = "multidex", version = "2.0.1" }
androidx-composeUi = { group = "androidx.compose.ui", name = "ui", version.ref = "composeVersion" }
androidx-uiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "composeVersion" }
androidx-activityCompose = { group = "androidx.activity", name = "activity-compose", version = "1.8.1" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version = "1.1.2" }
androidx-uiTooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "composeVersion" }
androidx-uiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "composeVersion" }
androidx-runtimeLiveData = { group = "androidx.compose.runtime", name = "runtime-livedata", version = "1.5.4" }
androidx-uiUtil = { group = "androidx.compose.ui", name = "ui-util", version.ref = "composeVersion" }
androidx-hiltNavigationCompose = { group = "androidx.hilt", name = "hilt-navigation-compose", version = "1.2.0" }

#Test
androidx-junit = { group = "androidx.test.ext", name = "junit", version = "1.1.5" }
androidx-uiTestJunit = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "composeVersion" }
androidx-espressoCore = { group = "androidx.test.espresso", name = "espresso-core", version = "3.5.1" }

#Room
androidx-roomRuntime = { group = "androidx.room", name = "room-runtime", version.ref = "roomVersion" }
androidx-roomCompiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomVersion" }
androidx-roomKtx = { group = "androidx.room", name = "room-ktx", version.ref = "roomVersion" }

#App compat
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appCompatVersion" }
androidx-appcompatResource = { group = "androidx.appcompat", name = "appcompat-resources", version.ref = "appCompatVersion" }

#Retrofit
squareup-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofitVersion" }
squareup-okhttp3Bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version = "4.11.0" }
squareup-okhttp = { group = "com.squareup.okhttp3", name = "okhttp" }
squareup-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor" }
squareup-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofitVersion" }

#Google
google-gson = { group = "com.google.code.gson", name = "gson", version = "2.10.1" }
google-hiltAndroid = { group = "com.google.dagger", name = "hilt-android", version.ref = "daggerHiltVersion" }
google-hiltCompoiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "daggerHiltVersion" }
google-systemUiController = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanistVersion" }
google-placeHolderMaterial = { group = "com.google.accompanist", name = "accompanist-placeholder-material", version.ref = "accompanistVersion" }
google-playServiceLocation = { group = "com.google.android.gms", name = "play-services-location", version = "21.0.1" }
google-playServiceAuth = { group = "com.google.android.gms", name = "play-services-auth", version = "20.7.0" }
google-mapsCompose = { group = "com.google.maps.android", name = "maps-compose", version = "2.14.0" }
google-mapsKtx = { group = "com.google.maps.android", name = "maps-ktx", version.ref = "mapsUtilVersion" }
google-utilsKtx = { group = "com.google.maps.android", name = "maps-utils-ktx", version.ref = "mapsUtilVersion" }
google-utils = { group = "com.google.maps.android", name = "android-maps-utils", version = "3.8.0" }
google-composeMapsUtils = { group = "com.google.maps.android", name = "maps-compose-utils", version.ref = "composeMapsVersion" }
google-composeMapsWidgets = { group = "com.google.maps.android", name = "maps-compose-widgets", version.ref = "composeMapsVersion" }
google-playServiceMaps = { group = "com.google.android.gms", name = "play-services-maps", version = "18.2.0" }
google-place = { group = "com.google.android.libraries.places", name = "places", version = "3.2.0" }
google-placeKtx = { group = "com.google.maps.android", name = "places-ktx", version = "2.0.0" }

#Coil
coil-compose = { group = "io.coil-kt", name = "coil-compose", version = "2.4.0" }

#Coroutine
jetbrains-kotlinxCoroutineAndroid = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version = "1.7.3" }

#Joda
joda-time = { group = "joda-time", name = "joda-time", version = "2.12.5" }

#Junit
junit = { group = "junit", name = "junit", version = "4.13.2" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidPluginVersion" }
android-library = { id = "com.android.library", version.ref = "androidPluginVersion" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "1.9.20" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "1.9.20" }
google-daggerHiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "daggerHiltVersion" }
google-mapsplatform = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version = "2.0.1" }
kotlin-parcelize = { id = "kotlin-parcelize" }